USE [master]
GO

/****** Object:  Database [SAPE]    Script Date: 9/3/2013 5:41:53 PM ******/
DROP DATABASE [SAPE]
GO

/****** Object:  Database [SAPE]    Script Date: 9/3/2013 5:41:53 PM ******/
CREATE DATABASE [SAPE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SAPE', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\SAPE.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SAPE_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\SAPE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SAPE] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SAPE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SAPE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SAPE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SAPE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SAPE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SAPE] SET ARITHABORT OFF 
GO

ALTER DATABASE [SAPE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SAPE] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SAPE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SAPE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SAPE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SAPE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SAPE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SAPE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SAPE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SAPE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SAPE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SAPE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SAPE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SAPE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SAPE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SAPE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SAPE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SAPE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SAPE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SAPE] SET  MULTI_USER 
GO

ALTER DATABASE [SAPE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SAPE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SAPE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SAPE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SAPE] SET  READ_WRITE 
GO

