//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Empresa = new HashSet<Empresa>();
            this.Profesor = new HashSet<Profesor>();
        }
    
        public int idCiudad { get; set; }
        public string Nombre { get; set; }
        public int FK_Provincia { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<Profesor> Profesor { get; set; }
    }
}
