//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Empresa = new HashSet<Empresa>();
            this.PreferenciaDireccion = new HashSet<PreferenciaDireccion>();
        }
    
        public int idCiudad { get; set; }
        public string Nombre { get; set; }
        public int FK_Provincia { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<PreferenciaDireccion> PreferenciaDireccion { get; set; }
    }
}
