//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.CursoXEstudiante = new HashSet<CursoXEstudiante>();
        }
    
        public int idCurso { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<CursoXEstudiante> CursoXEstudiante { get; set; }
    }
}
