//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public Estudiante()
        {
            this.CursoXEstudiante = new HashSet<CursoXEstudiante>();
            this.Evaluacion = new HashSet<Evaluacion>();
            this.PreferenciaProfesor = new HashSet<PreferenciaProfesor>();
        }
    
        public int idEstudiante { get; set; }
        public int FK_Persona { get; set; }
        public Nullable<int> FK_Proyecto { get; set; }
        public int Carnet { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<CursoXEstudiante> CursoXEstudiante { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
        public virtual ICollection<PreferenciaProfesor> PreferenciaProfesor { get; set; }
    }
}
