//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        public int idEvaluacion { get; set; }
        public decimal Nota { get; set; }
        public int FK_TipoEvaluacion { get; set; }
        public int FK_Estudiante { get; set; }
        public int Evaluador { get; set; }
        public Nullable<int> FK_Empresa { get; set; }
        public Nullable<int> FK_Profesor { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        public virtual Profesor Profesor { get; set; }
        public virtual TipoEvaluacion TipoEvaluacion { get; set; }
    }
}
