//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Contacto = new HashSet<Contacto>();
            this.Estudiante = new HashSet<Estudiante>();
            this.Profesor = new HashSet<Profesor>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idPersona { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
    
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual ICollection<Estudiante> Estudiante { get; set; }
        public virtual ICollection<Profesor> Profesor { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
