//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Contacto = new HashSet<Contacto>();
            this.Empresa = new HashSet<Empresa>();
            this.Estudiante = new HashSet<Estudiante>();
            this.Profesor = new HashSet<Profesor>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idPersona { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
    
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<Estudiante> Estudiante { get; set; }
        public virtual ICollection<Profesor> Profesor { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
