//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferenciaProfesor
    {
        public int idPreferencia { get; set; }
        public int FK_Estudiante { get; set; }
        public int FK_Profesor { get; set; }
        public int Valor { get; set; }
        public string Comentario { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
