//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferenciaDireccion
    {
        public int FK_Profesor { get; set; }
        public int FK_Direccion { get; set; }
        public int Prioridad { get; set; }
        public int id { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
