//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferenciaDireccion
    {
        public int FK_Profesor { get; set; }
        public int FK_Direccion { get; set; }
        public int Prioridad { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
