//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferenciaProfesor
    {
        public int idPreferencia { get; set; }
        public int FK_Estudiante { get; set; }
        public int FK_Profesor { get; set; }
        public int Valor { get; set; }
        public string Comentario { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
