//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public Profesor()
        {
            this.Evaluacion = new HashSet<Evaluacion>();
            this.PreferenciaDireccion = new HashSet<PreferenciaDireccion>();
            this.PreferenciaProfesor = new HashSet<PreferenciaProfesor>();
        }
    
        public int idProfesor { get; set; }
        public int FK_Persona { get; set; }
        public int Asesora { get; set; }
        public Nullable<int> CargaMinima { get; set; }
        public Nullable<int> CargaMaxima { get; set; }
        public string Comentario { get; set; }
    
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<PreferenciaDireccion> PreferenciaDireccion { get; set; }
        public virtual ICollection<PreferenciaProfesor> PreferenciaProfesor { get; set; }
    }
}
