//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.Estudiante = new HashSet<Estudiante>();
        }
    
        public int idProyecto { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }
        public int FK_Empresa { get; set; }
        public Nullable<int> FK_Estado { get; set; }
        public string Observacion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual EstadoProyecto EstadoProyecto { get; set; }
        public virtual ICollection<Estudiante> Estudiante { get; set; }
    }
}
