//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEvaluacion
    {
        public TipoEvaluacion()
        {
            this.Evaluacion = new HashSet<Evaluacion>();
        }
    
        public int idTipoEvaluacion { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
    }
}
